# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: NAROTTAM
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/narottam.github.io" # the subpath of the site
url:  # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: App

footer:
#  contact:
#   - name: Email
#      value: yourmail@domain.com
 #     link: mailto:yourmail@domain.com
  #follow:
   # - name: Facebook
    #  link: http://facebook.com/YourFacebookUsername
    #- name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    #- name: GitHub
     # link: http://github.com/YourGitHubUsername

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
